backend:
  name: git-gateway
  branch: main
  identity_url: https://heiskell.netlify.app/.netlify/identity
  gateway_url: https://heiskell.netlify.app/.netlify/git

media_folder: "uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "originals"
    label: "Originals"
    files:
      - file: "data/posts.json"
        name: "posts_json"
        label: "Heiskell Originals"
        fields:
          - label: "Posts"
            name: "posts"
            widget: "list"
            summary: "{{fields.title}} — {{fields.tag}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Summary", name: "summary", widget: "text" }
              - { label: "Image", name: "image", widget: "image", allow_multiple: false }
              - { label: "URL (optional)", name: "url", widget: "string", required: false }
              - { label: "Author", name: "author", widget: "string", default: "Staff" }
              - { label: "Tag", name: "tag", widget: "select", options: ["Top News","Business","Public Safety"], default: "Top News" }
              - { label: "Published At", name: "published_at", widget: "datetime" }
              - { label: "Publish?", name: "published", widget: "boolean", default: true }
