backend:
  name: git-gateway
  branch: main
  identity_url: "https://heiskell.netlify.app/.netlify/identity"
  gateway_url: "https://heiskell.netlify.app/.netlify/git"

media_folder: "uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "originals"
    label: "Originals"
    files:
      - file: "data/posts.json"
        name: "posts_json"
        label: "Heiskell Originals"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Summary"
            name: "summary"
            widget: "text"
          - label: "Body"
            name: "body"
            widget: "markdown"
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Date"
            name: "date"
            widget: "datetime"
          - label: "Author"
            name: "author"
            widget: "string"
          - label: "Tag"
            name: "tag"
            widget: "string"
